# @name Local
# @description Local API

### Variables
@base_url = http://localhost:3333

# @name Users
### POST users
POST {{base_url}}/v1/users HTTP/1.1
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example.com",
  "password": "123456"
}

# @name Authenticate
### POST authenticate
POST {{base_url}}/v1/authenticate HTTP/1.1
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "123456"
}

# @name UserProfile
### GET user profile
GET {{base_url}}/v1/users/{id}/profile HTTP/1.1
Content-Type: application/json